### PR TITLE
COL-2041 build out group filter functionality for asset library searc…

### PR DESCRIPTION
**Pull request by mlincoln**
…h + tests

https://jira-secure.berkeley.edu/browse/COL-2041

### CODE REVIEW

**Comment by johncrossman** [comment]
Looks good to me. Waiting on Travis.

**Comment by johncrossman** [comment]
@mlincoln - The Python linter failed as follows:

```
squiggy/models/asset.py:512:1: E302 expected 2 blank lines, found 1
def _build_order_clause(order_by):
^
tests/test_api/test_asset_controller.py:287:19: Q000 Double quotes found but single quotes preferred
            title="mock link",
                  ^
tests/test_api/test_asset_controller.py:289:17: Q000 Double quotes found but single quotes preferred
            url="https://www.example.com",
                ^
1     E302 expected 2 blank lines, found 1
2     Q000 Double quotes found but single quotes preferred
```

I dug up that error from Travis log: https://app.travis-ci.com/github/ets-berkeley-edu/squiggy/builds/257081241

**Comment by mlincoln** [comment]
Whoops, I tried to amend those issues, but messed up my (re)commit. 
They're fixed now, is there a way to re-trigger Travis?

**Comment by mlincoln** [comment]
Oh, nevermind, it's running again.

**Pull request merged**
