### PR TITLE
COL-1962 Emit socket event on asset preview update

### PR DESCRIPTION
**Pull request by pauline2k**
https://jira-secure.berkeley.edu/browse/COL-1962

Hard to test locally so this, too, is a bit of an experiment.

### CODE REVIEW

**Comment by johncrossman** [comment]
Looks good @pauline2k.  Have you seen the optional `PREVIEWS_CALLBACK_API_PREFIX` config?  That might help with testing locally. Not sure.

**Comment by johncrossman** [comment]
@pauline2k - In my local configs, I have the following.
```
PREVIEWS_CALLBACK_API_PREFIX = 'https://app3-dev.ets-berkeley-suitec.net/api'
```

**Comment by pauline2k** [comment]
@johncrossman Ah yes, thanks. The problem, I think, is that my local machine doesn't have a publicly accessible URL that the the preview service can call back to when it's finished processing. Will keep tinkering though.

**Comment by johncrossman** [comment]
@pauline2k - I do believe that config will fix your problem. I added it to the code for just the problem you're having. The preview service call back will go to squiggy-dev and update the db as necessary. Your local app will get the info from the db.

**Pull request merged**
