### PR TITLE
COL-2095: excludes deleted assets from activity timeline

### PR DESCRIPTION
**Pull request by lyttam**
https://jira-secure.berkeley.edu/browse/COL-2095

### CODE REVIEW

**Comment by pauline2k** [comment]
@lyttam So this will leave the activity on the timeline but not provide details or a link for associated assets if they're deleted? If that's the behavior, works for me.

**Comment by lyttam** [comment]
@pauline2k No, it would remove it entirely. Should it do what you suggested instead?

**Comment by pauline2k** [comment]
@lyttam Oh, you're right, the condition is a WHERE, not an ON, so will join and then filter out. That works too!

**Comment by pfarestveit** [comment]
The old behavior was that the activity itself vanished from the timeline, not just the asset. @lyttam @pauline2k

**Pull request merged**
