### PR TITLE
COL-2163 Replacing getCourse with lighter weight API calls to speed u…

### PR DESCRIPTION
**Pull request by mlincoln**
…p asset library load times
https://jira-secure.berkeley.edu/browse/COL-2163

### CODE REVIEW

**Comment by mlincoln** [comment]
Amended to make the SQL a bit more readable.

**Comment by johncrossman** [comment]
@mlincoln - I'm not surprised that our API tweaking caused test failures. The latest is in `test_course_controller.TestGetCourse`.  When Travis is green then I'm hoping @pauline2k or @lyttam can review this PR – an unbiased review.

**Comment by mlincoln** [comment]
Amending to fix the whitespace errors I introduced in my prior amendment

**Comment by mlincoln** [comment]
The failing test is trying to find a users value in api_json, 
`assert user.id in [user['id'] for user in api_json['users']]
`
but that value doesn't exist:
`{'active': True, 'assetLibraryUrl': None, 'canvas': {'canvasApiDomain': 'bcourses.berkeley.edu', 'name': 'bCourses', 'supportsCustomMessaging': False, 'useHttps': True, 'createdAt': '2023-02-27T23:22:43.475555+00:00', 'updatedAt': '2023-02-27T23:22:43.475583+00:00'}, 'canvasApiDomain': 'bcourses.berkeley.edu', 'canvasCourseId': 1502870, 'canvasGroups': [], 'enableDailyNotifications': True, 'enableUpload': True, 'enableWeeklyNotifications': True, 'engagementIndexUrl': None, 'id': 1, 'impactStudioUrl': None, 'lastPolled': None, 'name': None, 'protectsAssetsPerSection': False, 'whiteboardsUrl': None, 'createdAt': '2023-02-27T23:22:43.502072+00:00', 'updatedAt': '2023-02-27T23:22:43.502112+00:00'}`
Any tips on unraveling this?

**Comment by pauline2k** [comment]
@mlincoln It looks like your code change deliberately took the users list out of the '/api/course/<course_id>' feed. Assuming that's intended and desirable (the front end doesn't need the users list in that place), then I'd just change the test to match by removing the assertion around the users list.

**Comment by pauline2k** [comment]
@mlincoln And I'd probably add a test for get_advanced_asset_search_options with that same assertion, since that's where the users show up now.

**Comment by mlincoln** [comment]
That did it. Thanks @pauline2k !

**Comment by pauline2k** [comment]
Looks good to me!

**Pull request merged**
