### PR TITLE
COL-2196 Last Generated At datetime fix and expand access to regenera…

### PR DESCRIPTION
**Pull request by mlincoln**
…te button
https://jira-secure.berkeley.edu/browse/COL-2196

### CODE REVIEW

**Comment by mlincoln** [comment]
@pfarestveit thought this might open us to DDOS risk. If that's a concern, we could lock it down to instructors, or roll it back to admin-only.

**Comment by johncrossman** [comment]
@mlincoln - I vote for admin-only. That said, you are the service lead and you can decide on instructor-or-admin-only, if you have that opinion.  I agree with the DDOS concern.

**Comment by mlincoln** [comment]
@johncrossman I changed it to admin/instructor only:
This will allow an instructor to quickly clean up if there's an issue with the preview service in the future; meaning that the service lead doesn't have to respond as quickly, and the regeneration of assets can be distributed.

We already allow all users to regenerate link previews, and that's never been abused (to my knowledge).

**Comment by johncrossman** [comment]
Thanks @mlincoln

**Pull request merged**
