### PR TITLE
COL-2026: adds siloed column to courses table

### PR DESCRIPTION
**Pull request by lyttam**
https://jira-secure.berkeley.edu/browse/COL-2026

@johncrossman @mlincoln do you have a better idea for the column name?

### CODE REVIEW

**Comment by johncrossman** [comment]
@lyttam - How about `protects_assets_per_section`?

**Comment by johncrossman** [comment]
@lyttam - did you intentionally update the `package-lock.json` file?

**Comment by lyttam** [comment]
@johncrossman thanks, I changed it to `protects_assets_per_section`. The package-lock updates are due to running `npm i` while setting up my dev environment.

**Comment by johncrossman** [comment]
Thanks @lyttam

**Pull request merged**
