### PR TITLE
COL-2108 added an alert that displays when a user tries to upload a W…

### PR DESCRIPTION
**Pull request by mlincoln**
…EBP/HEIC formatted file
https://jira-secure.berkeley.edu/browse/COL-2108

This is pretty rudimentary, so I don't know if you want to merge it, or let it sit and review when we next meet. @johncrossman

### CODE REVIEW

**Comment by pauline2k** [comment]
Since we're not actually trying to block these uploads, I think rudimentary in this case might be just fine; but will defer to @johncrossman here.

**Comment by johncrossman** [comment]
@mlincoln - This is good. I'll merge and then we can build on it next time we meet.  Do we need to disable the 'Upload' button?

**Comment by johncrossman** [comment]
Ah, ignore my question on disabling. As Pauline says, we don't want to block the upload.

**Comment by mlincoln** [comment]
Yeah, this is informational only. Maybe there are other file formats we actually want to block.

I meant it's rudimentary in that it's hardcoded for webp/heic when there's certainly a more elegant/dynamic way to maintain a list of supported/unsupported file types to validate against.

**Pull request merged**
